name: Generate PDF

on:
  push:
    branches:
      - master

jobs:
  pdf:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mkrakowitzer/actions-makepdfs@v1.2
        with:
          markdown_dir: 
          output_dir: pdf
      - uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: pdf
